"""Metadatos CURADOS a mano para el cuaderno de Colab (Colab_Avance_MPSR_v1) y docs/Documentacion_Codigo_v1.md.

Los usa scripts/construir_colab.py, que los guarda en recursos/metadatos.json dentro del paquete público; el cuaderno solo los muestra. Aquí vive lo que no se puede deducir del código:
el paso del protocolo de cada script, sus entradas y salidas, el glosario de métricas, la matriz de trazabilidad y lo que verifica cada prueba.
Nada de esto contiene frases de participantes.
"""

# nombre del script -> (paso del protocolo, entradas, salidas, rol en el cuaderno)
SCRIPTS = {
    "common.py": ("Transversal (P06)", "—", "Funciones: ROOT, normalize (jerga local), file_sha256, load_jerga", "Documentado (lo importan casi todos los demás)"),
    "libro_xml.py": ("T03.1 (lote real)", ".xlsx de transcripción", "Mismo .xlsx con celdas editadas en el XML (conserva validaciones y fórmulas)", "Documentado"),
    "deteccion_simulado.py": ("2.14 (datos simulados)", "Libros .xlsx y tablas", "Decisión «¿es simulado/sintético?»; bloquea que lo simulado cuente como real", "Documentado (impide mezclar rótulos)"),
    "expand_corpus.py": ("P02", "corpus v1 (2 grupos por intención)", "corpus v2 (4 grupos por intención, 648 frases)", "Documentado"),
    "apply_ampliacion_v3.py": ("P02", "corpus v2 + corpus/ampliacion_v3.csv", "corpus v3 (708 frases sintéticas)", "Documentado"),
    "audit_corpus.py": ("P03, P04", "corpus/corpus_metadata.csv", "logs/audit_report.txt, corpus/corpus_audit.csv, corpus_summary.json", "Lógica recalculada (etapa 4)"),
    "split_corpus.py": ("P05", "corpus_metadata.csv", "corpus/dataset_split.csv (train/validation/test agrupados por base_phrase_id)", "Lógica recalculada (etapa 4)"),
    "export_rasa_nlu.py": ("P06, P08", "Corpus particionado", "data/nlu_{train,validation,test}.yml (formato Rasa)", "Documentado"),
    "train_baseline_p07.py": ("P07 (versión inicial)", "Corpus v1 real de 324 frases", "logs/EXP_BASELINE_SVM_S42_2026/", "Documentado (histórico)"),
    "train_baseline.py": ("P07, P10, P11", "corpus + configs/baseline_config.json", "logs/<experimento>/ con métricas y predicciones (TF-IDF + SVM y regresión logística)", "Lógica reproducida en pequeño (etapa 5, sintético)"),
    "run_rasa_grid.py": ("P08, P10, P11", "data/*.yml + configs/rasa_config.yml", "logs/RASA-e<epochs>-b<batch>-d<dim>-s<semilla>/", "Documentado (requiere Rasa)"),
    "crossval_agrupada.py": ("P11", "Corpus sintético", "Validación cruzada agrupada por base_phrase_id", "Documentado (requiere Rasa)"),
    "smoke_test.py": ("P11.1", "tests/smoke_test_queries*.csv + modelo", "Predicción de las 54 intenciones (equivalente a rasa shell)", "Documentado (requiere Rasa)"),
    "plot_p11_1.py": ("P11.1", "Resultados de P11.1", "Figuras de evidencias/p11_1_pruebas/", "Documentado"),
    "plot_v3_comparacion.py": ("P11.1 (reevaluación)", "Resultados v2 y v3", "Figuras de comparación v2 (648) vs v3 (708)", "Documentado"),
    "aplicar_tupa.py": ("P09, G4", "docs/tupa/Verificacion_TUPA_v*.xlsx + domain", "domain.yml / domain_v3.yml con respuestas verificadas; informe .md", "Documentado (con respaldo y dry-run)"),
    "aplicar_respuestas.py": ("P09, G4", "docs/tupa/respuestas_manual_20261008.yml + Verificacion_TUPA", "domain.yml / domain_v3.yml actualizados; informe", "Documentado (con respaldo y dry-run)"),
    "humo_respuestas.py": ("P09, G4", "domain.yml, domain_v3.yml", "Prueba de humo: 54 intenciones con utter_<intención> sin placeholders", "Lógica recalculada (etapa 9)"),
    "catalogo_formularios.py": ("T03 (lote real)", "—", "Catálogo de formularios A–F del lote 1", "Documentado"),
    "preparar_libro_v13.py": ("T03 (lote real)", "Plantilla vacía V1.2", "Lote1_Transcripcion_V1.3.xlsx vacío", "Documentado"),
    "ampliar_libro.py": ("T03 (lote real)", "Libro de transcripción + complemento", "Libro ampliado (participantes y situaciones nuevas)", "Documentado"),
    "combinar_libros.py": ("T03 (lote real)", "Libro BASE y libro FUENTE", "BASE con celdas de entrada de la FUENTE (edición del XML)", "Documentado"),
    "ingest_real_lote.py": ("T03.1 (ingesta), lotes 1 y 2", "Libro de transcripción lleno (frases reales)", "corpus/real*/ (validado, final, alertas), reporte de ingesta, «Listo para la Parte B»", "Documentado (no se ejecuta: usa datos reales)"),
    "trasladar_revision.py": ("T03.1 (revisión)", "Libro Revision_Etiquetas (hoja Revision)", "corpus/real/lote1_revision_etiquetas.csv", "Documentado"),
    "conciliar_seguimiento.py": ("T03.1 (lote 1)", "Seguimiento del lote 1 + respuestas", "Conciliación y alertas de perfil", "Documentado"),
    "split_corpus_v3.py": ("P05, T05 (lote 1)", "Corpus sintético + lote 1 real validado", "corpus/v3_real/ (train sintético; validación y test reales), log de cambios", "Documentado (datos reales)"),
    "eval_real.py": ("P08, P10, P11 (lote 1)", "Partición v3 real", "logs/v3_real/ (F1 macro, selección por validación, test UNA vez)", "Documentado (el test del lote 1 ya se gastó)"),
    "fallback_threshold.py": ("T05 (umbral)", "Predicciones de validación", "Umbral t de confianza elegido en validación", "Documentado"),
    "crossval_participantes.py": ("Sensibilidad (V1.6)", "Frases reales del lote 1 por participante", "logs/avance/cv_participantes_*.md (no cuenta para G3)", "Documentado (requiere Rasa)"),
    "preparar_entrenamiento_lote2.py": ("Lote 2 (V1.6 5.8)", "707 sintéticas + 185 reales activas + 51 sintéticas nuevas", "corpus/v3_lote2/entrenamiento_lote2.csv (943 frases)", "Documentado (datos reales)"),
    "umbral_lote2.py": ("Lote 2 (G3)", "Validación cruzada por participante del lote 1", "logs/v3_real/lote2_umbral_congelado.json (t = 0,50)", "Documentado"),
    "entrenar_svm_lote2.py": ("Lote 2 (baseline)", "entrenamiento_lote2.csv", "models/svm/LOTE2-SVM.joblib", "Documentado (el SVM del lote 2 ya está congelado)"),
    "hoja_revision_lote2.py": ("Lote 2 (revisión)", "Frases del lote 2 ingestadas", "Excel de revisión de etiquetas (privado)", "Documentado (datos reales)"),
    "informe_ingesta_lote2.py": ("Lote 2", "Ingesta del lote 2", "logs/avance/ingesta_lote2_cifras.md (solo cifras e ids)", "Documentado"),
    "split_lote2.py": ("Lote 2 (P05)", "Revisión aplicada + entrenamiento + congelamiento previo", "corpus/v3_lote2/ (solo test; 13 frases idénticas al entrenamiento excluidas por coincidencia exacta)", "Lógica recalculada (etapa 4)"),
    "eval_lote2.py": ("Lote 2 — evaluación ÚNICA (G3)", "Modelo congelado + partición del lote 2", "logs/v3_real/lote2/ (predicciones, F1, IC), logs/avance/eval_lote2_*", "NO se ejecuta: el cuaderno recalcula desde las predicciones guardadas (etapa 7)"),
    "congelar_modelo.py": ("G5", "Modelo, dominio, entrenamiento, configuración, umbral", "logs/v3_real/modelo_congelado.json; opción --verificar", "Lógica recalculada (etapa 6)"),
    "asistente_local.py": ("P11.2b (pre-piloto), T08", "Modelo congelado + domain_v3.yml", "Consola que responde con utter_<intención> o «no entendí»; log por sesión en carpeta privada", "Documentado (requiere Rasa; NO se ejecuta aquí)"),
    "preparar_registro_prepiloto.py": ("P11.2b", "Plantilla Registro_Sesiones_Piloto_v2.xlsx", "Registro_Sesiones_Prepiloto.xlsx (Parametros: LOTE2-FINAL v1 y fecha de congelamiento)", "Documentado"),
    "analizar_piloto.py": ("P12–P14 (piloto), usa el registro de sesiones", "Registro de sesiones (.xlsx) elegibles", "Análisis del piloto sobre sesiones elegibles: tiempos, alfa de Cronbach, prueba final del modelo (UNA vez)", "Documentado — NO ejecutado sobre datos reales (gastaría la prueba final única)"),
    "estado_compuertas.py": ("2.14 (G1–G7)", "Archivos de evidencia de logs/ y docs/", "logs/avance/estado_compuertas.{json,md}", "Resultado guardado (etapa 12)"),
    "verificar_referencias.py": ("P15/P16", "Protocolo V1.8 y Nota v11 + repositorio", "Informe con 61 afirmaciones del protocolo/Nota: 59 OK y 0 discrepancias (cifras citadas frente a archivos)", "Documentado"),
    "auditar_diseno_piloto.py": ("P12 (auditoría)", "Documentos del repositorio", "Menciones al diseño anterior (120 personas) frente al vigente (n = 60)", "Documentado"),
    "auditar_fecha_corte.py": ("2.14 (auditoría)", "Documentos del repositorio", "Menciones a «fecha de corte» frente a las compuertas", "Documentado"),
    "demostracion_simulada.py": ("2.14 (demostración)", "Lote1_Transcripcion_SIMULADO_v2.xlsx y Registro_Sesiones_Piloto_SIMULADO_v4.xlsx", "evidencias/simulado_demostracion/<ejecución>/ (6 etapas + informe)", "Resultado guardado (etapa 15, Simulado)"),
    "construir_colab.py": ("Documentación (Colab)", "Repositorio (solo lectura) + tests/", "colab_paquetes/*.zip, notebooks/Colab_Avance_MPSR_v1.ipynb, docs/Documentacion_Codigo_v1.md", "Documentado (genera este cuaderno y los paquetes)"),
    "colab_metadatos.py": ("Documentación (Colab)", "—", "Tablas curadas (paso del protocolo, glosario, trazabilidad) que lee construir_colab.py", "Documentado"),
    "stats_analysis.py": ("P14", "Datos de línea base y de sesiones", "Pruebas de normalidad, t pareada o Wilcoxon, tamaño del efecto", "Documentado"),
    "simular_analisis_p14.py": ("P14 (ilustrativo)", "Datos inventados", "Demuestra que el pipeline estadístico corre", "Documentado (Simulado)"),
    "simular_P14_n120.py": ("P14 (ilustrativo)", "Línea base simulada P01 (n = 120)", "Resultados simulados de P14", "Documentado (Simulado)"),
}

# glosario de métricas: (término, definición, fórmula, cómo se interpreta, limitación)
GLOSARIO = [
    ("F1 macro", "Promedio simple del F1 de cada intención (todas pesan igual).", "F1_i = 2·P_i·R_i/(P_i+R_i); F1 macro = (1/K)·Σ F1_i", "0 = nada acertado, 1 = perfecto. Criterio de G3: ≥ 0,75.",
     "Con 4–5 frases por intención, cada error mueve mucho el F1 de esa intención. En este proyecto el promedio incluye la etiqueta «nlu_fallback» (abstención) cuando aparece como predicción, y cuenta como error."),
    ("Exactitud (accuracy)", "Proporción de frases cuya intención predicha coincide con la esperada.", "aciertos / total", "Fácil de leer, pero no distingue entre intenciones frecuentes y raras.", "Las abstenciones cuentan como error."),
    ("Cobertura", "Proporción de frases que el asistente RESPONDE (no se abstiene).", "(total − abstenciones) / total", "Más cobertura = menos «no entendí».", "Subir la cobertura bajando el umbral suele bajar la precisión."),
    ("Precisión de lo respondido", "Entre las frases respondidas, proporción de aciertos.", "aciertos / (total − abstenciones)", "Mide la confiabilidad de lo que el asistente dice.", "Es condicional a responder: no premia ni castiga abstenerse."),
    ("Abstención", "El asistente responde «no entendí» cuando la confianza es < t (0,50) o cuando la diferencia con la segunda intención es < 0,1.", "confianza_1 < t  o  confianza_1 − confianza_2 < 0,1", "Prefiere callar a responder mal.", "El FallbackClassifier está dentro del pipeline congelado: las predicciones traen la etiqueta «nlu_fallback»."),
    ("IC95 % bootstrap por frases", "Intervalo para el F1 macro obtenido remuestreando FRASES con reemplazo (1000 veces, semilla 42).", "percentiles 2,5 y 97,5 de los F1 remuestreados", "Si el límite inferior supera 0,75, el criterio se sostiene incluso con el azar del muestreo de frases.", "Supone frases independientes; con pocas frases por intención el IC por percentiles queda sesgado hacia abajo (por eso se informa también la media del bootstrap)."),
    ("IC95 % bootstrap por participantes", "Igual, pero remuestreando PARTICIPANTES completos (las frases de una misma persona no son independientes).", "ídem, por conglomerados", "Es el IC más honesto para generalizar a otras personas.", "Solo 25 participantes y 56 situaciones: sigue siendo una muestra pequeña y de conveniencia."),
    ("McNemar exacto", "Compara dos clasificadores sobre las MISMAS frases mirando solo las discordantes (donde uno acierta y el otro no).", "p = 2·P(X ≤ min(b,c)), X ~ Binomial(b+c, 0,5)", "p alto = no hay evidencia de que uno sea mejor que el otro.", "Con pocas discordantes (24 aquí) tiene poca potencia."),
    ("Alfa de Cronbach", "Consistencia interna de una escala de k ítems.", "α = k/(k−1) · (1 − Σ var(ítem_i) / var(suma))", "≥ 0,70 se considera aceptable (criterio de G6).", "Con n = 5 es muy inestable; un alfa bajo con n pequeño no permite concluir cuál ítem falla."),
    ("Kappa de Cohen", "Acuerdo entre dos juicios corregido por el azar.", "κ = (p_o − p_e)/(1 − p_e)", "1 = acuerdo perfecto; 0 = el que daría el azar.", "En este proyecto, el «kappa» del lote 2 compara la etiqueta esperada con la revisión de UNA sola revisora: NO es acuerdo entre revisores."),
    ("Umbral de confianza t", "Valor mínimo de confianza para que el asistente responda.", "t = 0,50 (elegido con validación cruzada por participante del lote 1 y congelado antes de abrir el lote 2)", "Más alto = más abstenciones y más precisión.", "Se eligió con datos del lote 1; no se ajustó con el lote 2."),
]

# matriz de trazabilidad: (id, paso/compuerta, script(s), archivo de evidencia, resultado, estado)
TRAZA_PASOS = [
    ("P01", "Diagnóstico y línea base de tiempos", "simular_P14_n120.py", "corpus/Encuestas_simuladas_TramiFacil_MPSR_120_v2.xlsx", "Línea base SIMULADA (n = 120) del diseño V1.2; no es dato de campo", "simulado"),
    ("P02", "Construcción del corpus", "expand_corpus.py, apply_ampliacion_v3.py", "corpus/corpus_metadata.csv", "708 frases sintéticas, 54 intenciones, 9 categorías", "ejecutado"),
    ("P03", "Auditoría del corpus", "audit_corpus.py", "logs/audit_report.txt, corpus/corpus_audit.csv", "Duplicados y desbalance auditados", "ejecutado"),
    ("P04", "Control de fuga por paráfrasis", "audit_corpus.py", "corpus/corpus_summary.json", "leaks_detected = 0 en la partición v3", "ejecutado"),
    ("P05", "Partición train/validation/test", "split_corpus.py, split_corpus_v3.py, split_lote2.py", "corpus/dataset_split.csv; corpus/v3_real; corpus/v3_lote2", "546/81/81 sintético; lote 1 real 707/71/114; lote 2 solo test (267)", "ejecutado"),
    ("P06", "Normalización (jerga) y formato Rasa", "common.py, export_rasa_nlu.py", "configs/jerga_local.csv; data/*.yml", "Corpus exportado a formato Rasa", "ejecutado"),
    ("P07", "Línea base TF-IDF + SVM", "train_baseline_p07.py, train_baseline.py", "logs/baseline_validation.csv, logs/baseline_test.csv", "SVM C = 10 elegido en validación", "ejecutado"),
    ("P08", "Rasa NLU / DIET (grilla)", "run_rasa_grid.py, eval_real.py", "logs/v3_real/RASA-*", "Grilla epochs {100,150,200} × batch {64,128} × dim {20,50}", "ejecutado"),
    ("P09", "Respuestas del dominio", "aplicar_tupa.py, aplicar_respuestas.py, humo_respuestas.py", "domain_v3.yml; docs/tupa/Verificacion_TUPA_v10_4.xlsx", "44 respuestas de trámites, 0 con [Verificar]", "ejecutado"),
    ("P10", "Repeticiones con 5 semillas", "run_rasa_grid.py, train_baseline.py", "logs/v3_real/RASA-e100-b64-d20-s10…s50", "Semillas 10, 20, 30, 40, 50", "ejecutado"),
    ("P11", "Evaluación en el test", "eval_real.py, eval_lote2.py", "logs/v3_real/test_registro.json; logs/v3_real/lote2/", "Lote 1: F1 0,6867 (No cumplida, lote 1). Lote 2 (evaluación única): F1 0,9072", "ejecutado"),
    ("P11.1", "Pruebas técnicas internas", "smoke_test.py, plot_p11_1.py", "evidencias/p11_1_pruebas/", "46/54 intenciones correctas en el smoke test; CV 0,778 inflada por fuga", "ejecutado"),
    ("P11.2b", "Pre-piloto (G6)", "asistente_local.py, preparar_registro_prepiloto.py, estado_compuertas.py", "docs/piloto/privado/Registro_Sesiones_Prepiloto.xlsx (privado)", "7 sesiones, 5 elegibles; alfa 0,366 con n = 5 (< 0,70)", "ejecutado"),
    ("P12", "Piloto exploratorio (60 sesiones asistidas)", "analizar_piloto.py", "docs/piloto/privado/Registro_Sesiones_Piloto*.xlsx", "Sin sesiones reales aún; solo demostración simulada", "pendiente"),
    ("P13", "Recolección y cierre del piloto", "analizar_piloto.py, estado_compuertas.py", "logs/avance/cierre_piloto.txt", "No existe cierre declarado", "pendiente"),
    ("P14", "Análisis estadístico", "stats_analysis.py, analizar_piloto.py, simular_*", "evidencias/simulado_demostracion/…/05_sesiones", "Solo simulado; el análisis real depende de G6 y G7", "simulado"),
    ("P15", "Evidencias reproducibles", "congelar_modelo.py, verificar_referencias.py", "evidencias/, requirements-lock.txt", "Entorno fijado y huellas sha256", "ejecutado"),
    ("P16", "Bitácora de incidencias", "—", "incident_log.csv", "Una fila por incidencia o desviación", "ejecutado"),
]

# gates: (id, nombre, script, evidencia)
TRAZA_COMPUERTAS = [
    ("G1", "Lote 1 completo", "ingest_real_lote.py", "logs/v3_real/ingesta_reporte.txt"),
    ("G2", "Parte B ejecutada", "ingest_real_lote.py", "logs/v3_real/ingesta_reporte.txt + logs/avance/revision_pii.txt"),
    ("G3", "Calidad con lenguaje real", "eval_real.py, eval_lote2.py", "logs/v3_real/test_registro.json + logs/v3_real/lote2/test_registro.json"),
    ("G4", "Respuestas verificadas", "aplicar_tupa.py, aplicar_respuestas.py", "docs/tupa/Verificacion_TUPA_v10_4.xlsx"),
    ("G5", "Modelo congelado", "congelar_modelo.py", "logs/v3_real/modelo_congelado.json"),
    ("G6", "Pre-piloto", "asistente_local.py, estado_compuertas.py", "docs/piloto/privado/Registro_Sesiones_Prepiloto.xlsx"),
    ("G7", "Sesiones del piloto", "analizar_piloto.py, estado_compuertas.py", "docs/piloto/privado/Registro_Sesiones_Piloto*.xlsx + logs/avance/cierre_piloto.txt"),
]

# qué verifica cada prueba automática y por qué importa
PRUEBAS = {
    "smoke_compuertas.py": ("Tablero de compuertas G1–G7 con datos FALSOS: cada compuerta cambia de estado solo cuando corresponde, G6 lee solo Registro_Sesiones_Prepiloto.xlsx, lo simulado nunca cuenta como real y no se modifica corpus/real ni logs/v3_real.", "Si el tablero se equivocara, se declararían avances que no existen."),
    "smoke_piloto.py": ("Análisis del piloto con datos y predictor FALSOS: lectura del registro (encabezado en fila 2 o 3), alfa de Cronbach contra numpy, prueba final única, congelamiento (--verificar detecta cambios), la plantilla real vacía no produce resultados.", "Garantiza que el análisis del piloto es correcto y que no se puede gastar dos veces la prueba final."),
    "smoke_asistente.py": ("Asistente de consola con un modelo de 3 épocas entrenado con corpus sintético: se niega a iniciar si el congelamiento cambió o el registro no está ignorado por Git; responde utter_<intención> o «no entendí» según el umbral; no imprime intención ni confianza; no altera el congelamiento real.", "El pre-piloto usa este asistente: debe respetar el modelo congelado y la privacidad."),
    "smoke_lote2.py": ("Flujo del lote 2 con datos FALSOS: puerta de congelamiento, exclusión de frases idénticas al entrenamiento solo por coincidencia exacta, evaluación única (el registro se escribe antes de predecir), IC por frases y participantes.", "Asegura que la prueba independiente de G3 no se pueda contaminar ni repetir."),
    "smoke_lote_real.py": ("Flujo del lote 1 con datos FALSOS fuera del repositorio: ingesta, revisión, partición v3, evaluación (--smoke), umbral y dominio v3 con FallbackClassifier.", "Protege el procedimiento antes de tocar datos reales."),
    "smoke_transcripcion.py": ("Lectura del libro de transcripción del lote 1 (ingest_real_lote.py --libro) y blancos derivados, con COPIAS del libro simulado y datos falsos.", "Si la lectura del libro fallara, se perderían o confundirían datos de campo."),
    "smoke_conciliar.py": ("conciliar_seguimiento.py con datos falsos: detecta respuestas ausentes, blancos con respuesta, transcritos sin respuestas y participantes no transcritos.", "Evita atribuir respuestas a participantes equivocados."),
    "smoke_aplicar_tupa.py": ("aplicar_tupa.py con un libro y un domain.yml FALSOS: el dry-run no escribe nada; --aplicar exige partición y evaluación; solo reemplaza las respuestas confirmadas y sin alerta.", "Las respuestas forman parte del modelo congelado (G4 antes de G5)."),
    "smoke_umbral_test.py": ("fallback_threshold.py --fase test: aplica el umbral congelado a predicciones de test falsas ya guardadas, sin reentrenar ni cargar ningún modelo.", "El umbral no puede elegirse mirando el test."),
}

# datos: (ruta, origen, descripción, generado por)
DATOS = [
    ("corpus/corpus_metadata.csv", "Sintético", "Inventario de las 708 frases sintéticas (v3): texto, intención, categoría, fuente, grupo de paráfrasis, partición.", "apply_ampliacion_v3.py"),
    ("corpus/dataset_split.csv", "Sintético", "Partición train/validation/test (semilla 42) por grupo de paráfrasis.", "split_corpus.py"),
    ("corpus/corpus_audit.csv", "Sintético", "Registro de auditoría: duplicados y desbalance.", "audit_corpus.py"),
    ("corpus/corpus_summary.json", "Sintético", "Totales, distribución y verificación de fuga.", "audit_corpus.py"),
    ("corpus/ampliacion_v3.csv", "Sintético", "60 frases coloquiales (20 grupos) añadidas en v3.", "apply_ampliacion_v3.py"),
    ("corpus/refinamiento_lote2/sinteticas_ciclo1.csv", "Sintético", "51 frases sintéticas del ciclo de refinamiento 1 (antes de abrir el lote 2).", "escrito por el equipo (refinamiento)"),
    ("data/nlu_train.yml", "Sintético", "Entrenamiento en formato Rasa.", "export_rasa_nlu.py"),
    ("data/nlu_validation.yml", "Sintético", "Validación en formato Rasa.", "export_rasa_nlu.py"),
    ("data/nlu_test.yml", "Sintético", "Test en formato Rasa.", "export_rasa_nlu.py"),
    ("domain_v3.yml", "Sintético", "Dominio: 54 intenciones, respuestas utter_<intención>, nlu_fallback y utter_no_entendi. Forma parte del modelo congelado.", "aplicar_tupa.py, aplicar_respuestas.py"),
    ("configs/rasa_config_lote2.yml", "Sintético", "Pipeline del modelo congelado (DIET 100/64/20, semilla 42, FallbackClassifier 0,50 / 0,1).", "escrito a mano"),
    ("configs/baseline_config.json", "Sintético", "TF-IDF + SVM lineal, C ∈ {0,1; 1; 10}, semilla 42.", "escrito a mano"),
    ("logs/baseline_validation.csv", "Sintético", "Métricas del baseline en validación (corpus sintético).", "train_baseline.py"),
    ("logs/baseline_test.csv", "Sintético", "Métricas del baseline en test (corpus sintético).", "train_baseline.py"),
    ("corpus/Encuestas_simuladas_TramiFacil_MPSR_120_v2.xlsx", "Simulado (demostración)", "Línea base P01 SIMULADA (n = 120) del diseño V1.2.", "inventado para el diseño"),
    ("docs/lote_real_1/ejemplos_simulados/Lote1_Transcripcion_SIMULADO_v2.xlsx", "Simulado (demostración)", "Libro de transcripción de demostración.", "inventado"),
    ("docs/piloto/ejemplos_simulados/Registro_Sesiones_Piloto_SIMULADO_v4.xlsx", "Simulado (demostración)", "Registro de sesiones de demostración (60 sesiones inventadas).", "inventado"),
    ("evidencias/simulado_demostracion/20261005_demostracion/INFORME_DEMOSTRACION_SIMULADA.md", "Simulado (demostración)", "Informe de la demostración completa simulada.", "demostracion_simulada.py"),
    ("corpus/v3_real/corpus_metadata_v3.csv", "Real", "Partición del lote 1 (sintético + 186 frases reales): contiene frases reales → solo estructura aquí.", "split_corpus_v3.py"),
    ("corpus/v3_real/dataset_split_v3.csv", "Real", "Partición del lote 1 sin texto.", "split_corpus_v3.py"),
    ("corpus/real/lote1_real_final.csv", "Real", "Frases reales validadas del lote 1 → solo estructura.", "ingest_real_lote.py"),
    ("corpus/real_lote2/lote2_real_final.csv", "Real", "Frases reales validadas del lote 2 (Q0001–Q0280) → solo estructura.", "ingest_real_lote.py --lote 2"),
    ("corpus/v3_lote2/entrenamiento_lote2.csv", "Real", "Entrenamiento del modelo congelado: 943 frases (707 sintéticas + 185 reales del lote 1 + 51 sintéticas nuevas) → solo estructura.", "preparar_entrenamiento_lote2.py"),
    ("corpus/v3_lote2/corpus_metadata_v3_lote2.csv", "Real", "Partición del lote 2: train 943, test 267, excluidas 13 → solo estructura.", "split_lote2.py"),
    ("docs/lote_real_2/log_exclusion_entrenamiento_lote2.csv", "Real", "Las 13 frases del lote 2 excluidas por ser idénticas al entrenamiento (solo identificadores y motivo).", "split_lote2.py"),
    ("logs/v3_real/lote2/predicciones_lote2.csv", "Real", "Predicciones del modelo congelado sobre el test del lote 2 (con texto) → solo estructura.", "eval_lote2.py"),
    ("logs/v3_real/lote2/predicciones_lote2_svm.csv", "Real", "Predicciones del SVM sobre el mismo test.", "eval_lote2.py"),
    ("docs/piloto/privado/Registro_Sesiones_Prepiloto.xlsx", "Real", "Registro real del pre-piloto (7 sesiones; incluye textos escritos por las personas) → solo estructura.", "preparar_registro_prepiloto.py + llenado a mano"),
    ("docs/piloto/Registro_Sesiones_Piloto_v2.xlsx", "Sintético", "Plantilla VACÍA del registro de sesiones (fórmulas de elegibilidad).", "escrito a mano"),
    ("logs/v3_real/modelo_congelado.json", "Real", "Huellas sha256, versiones y configuración del modelo congelado (sin frases).", "congelar_modelo.py"),
    ("logs/avance/eval_lote2_resumen.json", "Real", "Resultados agregados de la evaluación única del lote 2 (sin frases).", "eval_lote2.py"),
    ("logs/avance/estado_compuertas.json", "Real", "Estado de las 7 compuertas.", "estado_compuertas.py"),
    ("incident_log.csv", "Real", "Bitácora de incidencias y desviaciones (P16).", "escrito por el equipo"),
]
